language: java   # 声明构建语言环境

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。

jdk:
- oraclejdk8

before_cache:
- mvn clean
cache:
  directories:
  - $HOME/.m2
